[package]
name = "cork"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "5.0"       
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
warp = "0.3"
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.11"
clap = "4.1"               
